#!/usr/bin/env python3


import contextlib
import json
import locale
import os
import subprocess
import sys
import traceback
from functools import lru_cache
from pathlib import Path

ON_WINDOWS = os.name == "nt"
ENABLE_LOGGING = True

# assuming __file__ is .pixi/envs/<env>/libexec/conda
# or .pixi\envs\<env>\libexec\conda.bat\..\conda.py
PIXI_ENVIRONMENT_FILE = Path(__file__).resolve().parent.parent / "conda-meta" / "pixi"
DEFAULT_PIXI_EXECUTABLE_PATH = (
    Path(Path.home()) / ".pixi" / "bin" / f"pixi{'.exe' if ON_WINDOWS else ''}"
)
PIXI_HOMEBREW_PATH = Path("/opt/homebrew/bin/pixi")


def pixi(cmd):
    try:
        out = subprocess.check_output(["pixi", *cmd])
    except FileNotFoundError as e:
        # if pixi is not on PATH, try to run it from the default location
        # see https://pixi.sh/install.sh or https://pixi.sh/install.ps1
        if PIXI_HOMEBREW_PATH.exists():
            out = subprocess.check_output([str(PIXI_HOMEBREW_PATH), *cmd])
        elif DEFAULT_PIXI_EXECUTABLE_PATH.exists():
            out = subprocess.check_output([str(DEFAULT_PIXI_EXECUTABLE_PATH), *cmd])
        else:
            msg = "pixi not found. Is it installed in your PATH?"
            raise FileNotFoundError(msg) from e
    return out.decode(locale.getpreferredencoding())


@lru_cache
def manifest_path():
    if PIXI_ENVIRONMENT_FILE.exists():
        with PIXI_ENVIRONMENT_FILE.open(encoding="utf8") as f:
            return Path(json.load(f)["manifest_path"])

    # pixi < 0.24.0
    project_root = Path(__file__).resolve().parent.parent.parent.parent.parent
    manifest_path = project_root / "pixi.toml"
    if manifest_path.exists():
        return manifest_path
    manifest_path = project_root / "pyproject.toml"
    if manifest_path.exists() and manifest_path.read_text(encoding="utf8").find("[tool.pixi") != -1:
        return manifest_path
    msg = "Manifest file not found."
    raise FileNotFoundError(msg)


def pixi_root():
    return manifest_path().parent / ".pixi"


def std_pixi_args():
    return ["-q", "--no-progress", "--manifest-path", str(manifest_path())]


def pixi_json(cmd):
    return json.loads(pixi([*cmd, "--json"]))


def pixi_envs():
    platform = pixi_json(["info", *std_pixi_args()])["platform"]
    envs = pixi_json(["info", *std_pixi_args()])["environments_info"]
    return [env["prefix"] for env in envs if platform in env["platforms"]]


def print_json(data):
    print(json.dumps(data, indent=4))


def prefix_to_env(prefix):
    return Path(prefix).name


def pixi_env_cli_params(env):
    return ["-e", env] if env != "default" else []


def conda_info_envs_json():
    print_json(
        {
            "envs_dirs": [str(pixi_root() / "envs")],
            "conda_prefix": str(pixi_root() / "envs"),
            "envs": pixi_envs(),
        },
    )


def conda_list(args):
    assert args[1] == "-p" or args[1] == "-n" or args[1] == "--json"
    if args[1] == "--json":
        # >= 2025.3
        assert args[2] == "-n" or args[2] == "-p"
        env = prefix_to_env(args[3]) if args[2] == "-p" else args[3]

        assert len(args) == 4  # noqa: PLR2004
        out = pixi_json(["list", *std_pixi_args(), *pixi_env_cli_params(env)])

        out_transformed = [
            {
                # in the case of PyPi dependencies, some of the fields can be none
                "name": str(x.get("name")),
                "version": str(x.get("version")),
                "build_string": str(x.get("build")),
                "base_url": str(x.get("source")),
            }
            for x in out
        ]

        print(json.dumps(out_transformed))
    else:
        # < 2025.3
        env = prefix_to_env(args[2]) if args[1] == "-p" else args[2]
        assert len(args) == 3 or len(args) == 4  # noqa: PLR2004
        out = pixi_json(["list", *std_pixi_args(), *pixi_env_cli_params(env)])
        if len(args) == 3:  # noqa: PLR2004
            lines = ("{name} {version} {build}".format(**pkg) for pkg in out)
        else:
            # observed in PyCharm 2024.1 for Windows
            assert args[3] == "-e"
            lines = ("{name}={version}={build}".format(**pkg) for pkg in out)
        print("\n".join(lines))


def conda_run(args):
    assert args[1] == "-p" or args[1] == "-n"
    env = prefix_to_env(args[2]) if args[1] == "-p" else args[2]

    if os.name == "nt":
        # https://bugs.python.org/issue20451
        pixi_run_args = [f'"{arg}"' for arg in args[3:] if arg != "--no-capture-output"]
    else:
        pixi_run_args = [arg for arg in args[3:] if arg != "--no-capture-output"]

    cmd = ["pixi", "run", *std_pixi_args(), *pixi_env_cli_params(env), *pixi_run_args]
    try:
        os.execlp("pixi", *cmd)
    except FileNotFoundError as e:
        # if pixi is not on PATH, try to run it from the default location
        # see https://pixi.sh/install.sh or https://pixi.sh/install.ps1
        try:
            os.execlp(str(DEFAULT_PIXI_EXECUTABLE_PATH), *cmd)
        except FileNotFoundError:
            msg = "pixi not found. Is it installed in your PATH?"
            raise FileNotFoundError(msg) from e


def conda_update(args):
    assert args[1:4] == ["--dry-run", "--all", "--json"]
    assert args[4] == "-n" or args[4] == "-p"
    print('{"success": true, "message": "All requested packages already installed."}')


def main(args):  # noqa: C901
    if args == ["self-check"]:
        try:
            pixi(["--version"])
        except (FileNotFoundError, subprocess.CalledProcessError):
            print("'pixi' not found, is it on the $PATH?", file=sys.stderr)
            return 1
        pixi(["info", *std_pixi_args()])
        if not manifest_path().exists():
            print(
                f"pixi manifest path {manifest_path()!s} does not exist.",
                file=sys.stderr,
            )
            return 1
        if not pixi_root().exists():
            print(
                f"pixi root {pixi_root()!s} does not exist.",
                file=sys.stderr,
            )
            return 1
        print("Self-check successful.", file=sys.stderr)
    elif args in (["info", "--envs", "--json"], ["env", "list", "--json"]):
        # `conda env list --json` (used in CLion 2025.3) returns
        # the same as `conda info --envs --json`
        conda_info_envs_json()
    elif args[0] == "list":
        conda_list(args)
    elif args[0] == "run":
        conda_run(args)
    elif args[0] == "--version":
        print("conda 25.9.1")
    elif args[0] == "update":
        conda_update(args)
    elif args[0] == "activate":
        msg = f"{args!s}\n`conda activate` not implemented. PyCharm will fallback to `conda run`."
        raise NotImplementedError(msg)
    else:
        raise NotImplementedError(str(args))

    return 0


if __name__ == "__main__":
    args = sys.argv[1:]

    if ENABLE_LOGGING:
        cache_home = Path(os.getenv("XDG_CACHE_HOME") or "~/.cache").expanduser()
        with contextlib.suppress(OSError):
            Path.mkdir(cache_home, parents=True)
        logfile = cache_home / "pixi-pycharm.log"
        with Path.open(logfile, "a") as f:
            f.write("Attempting to run: " + str(args) + "\n")

    try:
        sys.exit(main(args))
    except Exception:
        if ENABLE_LOGGING:
            with Path.open(logfile, "a") as f:
                f.write(traceback.format_exc())
        raise
