line-length = 100

target-version = "py38"

include = ["tests/*.py", "conda"]

[lint]
select = ["ALL"]
ignore = [
    "D",
    "ANN",
    "S603",
    "COM812",
    "ISC001",
    "T201",
    "S607",
    "TRY003",
    "S101",
    "S606",
    "FBT001",
]
