name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        environment:
          - default
          - py38-pixi019
          - py312-pixi019
          - py38-pixi024
          - py312-pixi024
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          environments: ${{ matrix.environment }}
      - run: pixi run fmt-check
      - run: pixi run lint-check
      - run: pixi run test --color=yes
