name: Release if version changed

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: Quantco/ui-actions/version-metadata@5bfb8cebf0801e07c6a1c208a35b41637a3ff7fa # v1.0.20
        id: version-metadata
        with:
          file: ./pixi.toml
          token: ${{ secrets.GITHUB_TOKEN }}
          version-extraction-override: 'regex:version = "(.*)"'
      - run: |
          git tag v${{ steps.version-metadata.outputs.newVersion }}
          git push origin v${{ steps.version-metadata.outputs.newVersion }}
        if: steps.version-metadata.outputs.changed == 'true'
      - name: Create release
        if: steps.version-metadata.outputs.changed == 'true'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          generate_release_notes: true
          tag_name: v${{ steps.version-metadata.outputs.newVersion }}
          draft: false
